version: '3.8'

services:
  flask-app:
    restart: always
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    environment:
      PORT: "8070"
      FLASK_ENV: "production"
    ports:
      - "80:8070"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15.4-alpine3.18
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
